development: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  database: geo_note_development
  pool: 5

test:
  <<: *default
  database: geo_note_test
